logging:
  level:
    org.springframework.data.r2dbc: DEBUG
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/healthcheck_db
    username: postgres
    password:
server:
  error:
    include-message: always
    include-binding-errors: always
